version: "3.8"

services:
  backend:
    build: .
    image: service-app
    ports:
      - "8082:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/service-app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=service-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  network: {}

